application: dronin-autotown
version: 1
runtime: go
api_version: go1
default_expiration: "1m"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.git)/.*
- ^src

builtins:
- datastore_admin: on
- remote_api: on
- deferred: on

admin_console:
  pages:
  - name: AppStats
    url: /_ah/stats/

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static
  secure: never

# Backend stuff.
- url: /(async|batch|resend|update).*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
