application: dronin-autotown
module: py
version: 1
api_version: 1
runtime: python27
threadsafe: true

libraries:
- name: lxml
  version: "2.3"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.git)/.*
- ^src

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: ../static/favicon\.ico

- url: /convert
  script: convert.app
